[package]
name = "hongo"
version = "0.1.0"
authors = ["Ricardo B. Machado <ricardobm@gmail.com>"]
license = "MIT"
description = "Japanese Learning pad"
repository = "https://github.com/ricardobm/hongo/"
keywords = ["japanese"]

[dependencies]
