# See https://taskfile.dev/

version: '2'

vars:
  ARGS: ""

tasks:
  default:
    silent: true
    cmds:
      - echo
      - echo Run 'task --list' or 'task -l' for a summary of available tasks.
      - echo

  build:
    desc:   Builds the Rust application.
    silent: true
    sources:
      - src/**/*.rs
    generates:
      - target/debug/hongo
      - target/debug/hongo.exe
    cmds:
      - cargo build
      - echo

  run:
    desc:   Runs the application.
    deps:   [build]
    silent: true
    env:
      RUST_BACKTRACE: 1
      ROCKET_CLI_COLORS: off
    cmds:
      - target/debug/hongo {{.ARGS}}

  watch-check:
    desc: Runs a continuous check of the application source files
    cmds:
      - echo Starting the check watcher...
      - echo Execute 'task watch' to run the application
      - cargo watch -x check -w src -s 'touch .trigger'

  watch:
    desc: Runs the application in watch mode, monitoring the '.trigger'
          file generated by the `watch-check` task.
    env:
      RUST_BACKTRACE: 1
      ROCKET_CLI_COLORS: off
    cmds:
      - echo Monitoring the application
      - echo Execute 'task watch-check' to update the .trigger file
      - cargo watch --no-gitignore -w .trigger -x run

  web:
    desc: Runs the web application in watch mode.
    dir:  web/client
    env:
      BROWSER: chrome
    cmds:
      - npm start

  test:
    desc:   Runs tests
    silent: true
    env:
      RUST_BACKTRACE: 1
    cmds:
      - cargo test --all
