[package]
name = "dict-build"
version = "0.1.0"
description = "Japanese dictionary database builder"
keywords = ["japanese"]
publish = false

[dependencies]
lazy_static = "1.4"
regex = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zip = "0.5"
