[package]
name = "kotoba-server"
version = "0.1.0"
authors = ["Ricardo B. Machado <ricardobm@gmail.com>"]
license = "MIT"
description = "Japanese dictionary server backend"
repository = "https://github.com/ricardobm/kotoba/"
keywords = ["japanese"]

[dependencies]
